Patch 1
hiwhi/ember-cli-cloudinary pull request #5
Opened 2016-06-30 22:47 UTC by waelbeso

add jquery file upload validation support

// template.hbs
{{cloudinary-direct-file signatureEndpoint=signatureEndpoint onUploadDone=(action 'showThumbnail') 
onprocessfail=(action 'processfail')
}}

// controller.js
        processfail(e,data){
            console.log(data.files[data.index].error)
        },

2017-07-27 02:53 UTC, mileszim requested changes
Thanks for implementing all of these! It needs a bit of cleanup first, however.

2017-07-27 02:53 UTC, mileszim commented on addon/components/cloudinary-direct-file.js
> +    this.$().bind('fileuploadprocessfail', (e, data) => {
I'd prefer you use the cloudinary events instead, there is an equivalent one here https://github.com/cloudinary/cloudinary_js/blob/6eac8e5233e6c04e772dcc0f991d28ae4d668c2a/src/jquery-file-upload.coffee#L106-L107

2017-07-27 02:53 UTC, mileszim commented on addon/components/cloudinary-direct-file.js
> +    // consalt the jQuery File Upload for more evant
// Consult (typo). May also be more relevant to refer to the cloudinary js implementation wrapper around the jquery one as that's directly related to this.

2017-07-27 02:53 UTC, mileszim commented on index.js
> +var path = require('path');
Please stick with ember convention, remove 'use strict'; and the associated node module so that it is browser friendly.

2017-07-27 02:53 UTC, mileszim commented on addon/components/cloudinary-direct-file.js
> +      this.sendAction('onprocessfail', e, data);
can you rename this to onUploadFail to stick with convention?

2017-07-27 02:53 UTC, mileszim commented on addon/instance-initializers/cloudinary-config.js
> +export default {
Please remove and revert this file, stay with Ember addon conventions. Was this causing a problem for you? Additionally, you cannot use Ember (line 17) if it is not imported. Do not make Ember global.

2017-07-27 02:53 UTC, mileszim commented on index.js
> +    app.import(path.join(blueimpLoadImagePath,           'js/load-image.all.min.js'));
Don't attempt to make everything aligned, follow standard Ember convention as the original has it and you will do fine.

2017-08-03 13:37 UTC, AdriaRios commented
Congrats @waelbeso, this is very necessary.

Will you do the suggested changes?

2017-08-10 23:39 UTC, mileszim commented
Closing in favor of #10

2017-08-10 23:39 UTC, closed without merging